// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwvWGT9-KW5Mppce0Ja_iFkndtGsTxEI',
    appId: '1:612438853354:web:c28ee396fde74166667993',
    messagingSenderId: '612438853354',
    projectId: 'e-commerce-projectapp',
    authDomain: 'e-commerce-projectapp.firebaseapp.com',
    storageBucket: 'e-commerce-projectapp.firebasestorage.app',
    measurementId: 'G-DGZWGGMKE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKI8E5qNY7JxbzPfpIwmDUilRcnd4EeE',
    appId: '1:612438853354:android:fcaaff88f539d47c667993',
    messagingSenderId: '612438853354',
    projectId: 'e-commerce-projectapp',
    storageBucket: 'e-commerce-projectapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOpx9dcL74Y_G5mwUE87vqXoB6xhAgDZs',
    appId: '1:612438853354:ios:01c040fb7951b772667993',
    messagingSenderId: '612438853354',
    projectId: 'e-commerce-projectapp',
    storageBucket: 'e-commerce-projectapp.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOpx9dcL74Y_G5mwUE87vqXoB6xhAgDZs',
    appId: '1:612438853354:ios:01c040fb7951b772667993',
    messagingSenderId: '612438853354',
    projectId: 'e-commerce-projectapp',
    storageBucket: 'e-commerce-projectapp.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxwvWGT9-KW5Mppce0Ja_iFkndtGsTxEI',
    appId: '1:612438853354:web:a66bed48a1f52843667993',
    messagingSenderId: '612438853354',
    projectId: 'e-commerce-projectapp',
    authDomain: 'e-commerce-projectapp.firebaseapp.com',
    storageBucket: 'e-commerce-projectapp.firebasestorage.app',
    measurementId: 'G-SQP7E2DLCM',
  );
}
